export default [
    {
        id: 1, 
        bthTitle: "Spielbank Berlin",
        bthDescription: 'This is the most famous casino in Berlin, located in the Charlottenburg district. It offers classic games such as roulette, blackjack, poker, and slot machines. The casino\'s interior is designed in an elegant style, creating an atmosphere of luxury.',
        bthAddress: 'Marlene-Dietrich-Platz 1, 10785 Berlin',
        bthFeatures: 'One of the most famous casinos in Germany, offers poker, roulette, blackjack, and slot machine games',
        bthRules: 'Dress code (elegant style), age restriction – 18+',
        bthImage: require('../assets/images/bthCasDataImages/bthCasPlace1.png'),
        isTop: true,
        isPoker: false,
        isRoulette: true,
        IsSlots: true,
    },
    {
        id: 2, 
        bthTitle: "Casino Royal Berlin",
        bthDescription: 'Casino Royal is a stylish casino located in the heart of Berlin. It offers a variety of games, including roulette, blackjack, and numerous slot machines. The interior is designed in a modern style with elements of luxury, creating a pleasant atmosphere for visitors.',
        bthAddress: 'Kurfürstendamm 224, 10719 Berlin',
        bthFeatures: 'Regular poker tournaments',
        bthRules: 'Elegant style, age restriction – 18+',
        bthImage: require('../assets/images/bthDataImages/bthPlace2.png'),
        isTop: false,
        isPoker: true,
        isRoulette: true,
        IsSlots: false,
    },
    
    {
        id: 3, 
        bthTitle: "Admiral Casino Berlin",
        bthDescription: 'This is a small casino focused on slot machines and sports betting. It is located in the city center and offers a more accessible and informal experience.',
        bthAddress: 'Multiple locations throughout the city',
        bthFeatures: 'A simple and accessible place to play slots',
        bthRules: 'Don\'t forget to bring your ID, as you must be over 18 to enter, there\'s no strict dress code.',
        bthImage: require('../assets/images/bthCasDataImages/bthCasPlace3.png'),
        isTop: false,
        isPoker: false,
        isRoulette: true,
        IsSlots: true,
    },
    {
        id: 4, 
        bthTitle: "Tipico Casino Berlin",
        bthDescription: 'Casino Royal is a stylish casino located in the heart of Berlin. It offers a variety of games, including roulette, blackjack, and numerous slot machines. The interior is designed in a modern style with elements of luxury, creating a pleasant atmosphere for visitors.',
        bthAddress: 'Friedrichstraße 105, 10117 Berlin',
        bthFeatures: 'Wide selection of slot machines',
        bthRules: 'Entry is restricted to individuals over 18 years old, elegant attire required, use of mobile phones at gaming tables is prohibited.',
        bthImage: require('../assets/images/bthCasDataImages/bthCasPlace4.png'),
        isTop: false,
        isPoker: false,
        isRoulette: false,
        IsSlots: true,
    },
]